django/ToDoApp/ToDoApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('todo/', include('manageToDo.urls')),
]

django/ToDoApp/manageToDo/urls.py
from django.urls import path
from . import views

app_name = 'manageToDo'

urlpatterns = [
    path('', views.home, name='home'),
    path('delete/<list_id>', views.delete, name='delete'),
    path('cross/<list_id>', views.cross, name='cross'),
    path('uncross/<list_id>', views.uncross, name='uncross'),

]

django/ToDoApp/manageToDo/models.py
from django.db import models

# Create your models here.
class ToDoList(models.Model):
    item = models.CharField(max_length=250)
    completed = models.BooleanField(default=False)

    def __str__(self):
        return self.item + ' - ' + str(self.completed)

django/ToDoApp/manageToDo/forms.py
from django import forms
from .models import ToDoList

class ToDoListForm(forms.ModelForm):
    class Meta:
        model = ToDoList
        fields = ['item', 'completed']

django/ToDoApp/manageToDo/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib import messages

from .models import ToDoList
from .forms import ToDoListForm

# Create your views here.
def home(request):

    if request.method == 'POST':
        form = ToDoListForm(request.POST or None)

        if form.is_valid():
            form.save()
            all_items = ToDoList.objects.all()
            messages.success(request, (' Item has been Added to To-Do List ! '))

            return render(request, 'manageToDo/index.html', {'all_items': all_items})

    else:
        all_items = ToDoList.objects.all()

        return render(request, 'manageToDo/index.html', {'all_items': all_items})


def delete(request, list_id):
    item = ToDoList.objects.get(pk=list_id)
    item.delete()
    messages.success(request, ('Item has been Deleted !'))

    # redirect( 'link' )
    return redirect( reverse('manageToDo:home') )


def cross(request, list_id):
    item = ToDoList.objects.get(pk=list_id)
    item.completed = True
    item.save()

    return redirect( reverse('manageToDo:home') )

def uncross(request, list_id):
    item = ToDoList.objects.get(pk=list_id)
    item.completed = False
    item.save()

    return redirect( reverse('manageToDo:home') )

django/ToDoApp/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">

      <a class="navbar-brand" href="#"> To-Do App </a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse flex-row-reverse" id="navbarSupportedContent">
        <form class="form-inline" method="POST">
            {% csrf_token %}
            <input class="form-control mr-sm-2" type="search" placeholder="Add Item" name="item">
            <button class="btn btn-outline-secondary my-2 my-sm-0 form-control" type="submit"> Add To List </button>
        </form>
      </div>

    </nav>

    <br>
    
    <div class="container">

      {% block content %}
      <!-- <h1>Hello, world!</h1> -->
      {% endblock content%}

    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

django/ToDoApp/templates/manageToDo/index.html
{% extends 'base.html' %}

{% block content %}

    {% if messages %}

        {% for message in messages %} 
            <div class="alert alert-warning alert-dismissable fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}

    {% endif %}


    {% if all_items %}
        <table class='table table-bordered'>
            
            {% for things in all_items %}
                <tr>
                    
                    {% if things.completed %}
                        <td style='text-decoration: line-through;'> {{ things.item }} </td>
                        <td style='text-align:center; width:20%;'> <a href="{% url 'manageToDo:uncross' things.id %}">Uncross</a></td>
                    {% else %}
                        <td> {{ things.item }} </td>
                        <td style='text-align:center; width:20%;'> <a href="{% url 'manageToDo:cross' things.id %}">Cross</a></td>
                    {% endif %}
                    
                    <td style='text-align:center; width:20%;'> <a href="{% url 'manageToDo:delete' things.id %}">Delete</a></td>
                    
                </tr>
            {% endfor %}

        </table>
    {% endif %}


{% endblock content%}